project:
  type: website
  output-dir: docs
  
website:
  title: "CAP-394"
  favicon: "resources/CAP394-Icon.png" 
  sidebar:
    style: "docked"
    search: true  
    contents: auto
  navbar:
    logo: "resources/CAP394-Icon.png" 
    left:
      - href: index.qmd
        text: Home
      - 000-Intro.qmd
      - 600-Projects.qmd
  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - "resources/styles.scss"
    toc: true


chapters:
  - index.qmd
  - 000-Intro.qmd
  - 600-Projects.qmd
  - 610-Capes-GraduateProgramsProjects.qmd


