project:
  type: website
  output-dir: docs


website:
  title: "CAP-394"
  favicon: "Resources/Images/CAP394-Icon.png" 
  sidebar:
    logo: "Resources/Images/CAP394-Icon-Trim.png"
    style: "docked"
    search: true
    contents:
      - index.qmd  
      - section: "Lectures"
        contents:
        - 00-Lectures-Intro.qmd
        - 01-Lectures-WhatIs.qmd
        - 02-Lectures-Skills.qmd
      - section: "Visualization"
        contents:
        - 10-Visualization-Intro.qmd
      - section: "Projects"
        contents:
        - 20-Projects-Intro.qmd
        - 23-Projects-Supermarket.qmd
      - section: "Ideas Bank"
        contents:
        - 30-Ideas-Intro.qmd
  page-footer: 
    center: "<a href='https://linktr.ee/rafaeldcsantos'>Rafael Santos</a>" 






format:
  html:
    theme:
      - spacelab
      - "Resources/SCSS/styles.scss"
    toc: true


chapters:
  - index.qmd
  - 000-Intro.qmd
  - 600-Projects.qmd
  - 610-Capes-GraduateProgramsProjects.qmd


