project:
  type: website
  output-dir: docs


website:
  title: "CAP-394"
  favicon: "Resources/Images/CAP394-Icon.png" 
  sidebar:
    logo: "Resources/Images/CAP394-Icon-Trim.png"
    style: "docked"
    search: true
    contents:
      - index.qmd  
      - section: "Lectures"
        contents:
        - 00-Lectures-Intro.qmd
        - 01-Lectures-WhatIs.qmd
        - 02-Lectures-Skills.qmd
      #   - 03-Lectures-Data.qmd
      - section: "Cookbook"
        contents:
        - 20-Cookbook-Intro.qmd
      - section: "Visualization"
        contents:
        - 31-Visualizing-Shapefiles.qmd
      - section: "Projects"
        contents:
        - 50-Projects-Intro.qmd
        - 51-Projects-Amendments.qmd
      #   - 53-Projects-Supermarket.qmd
      # - section: "Ideas Bank"
      #   contents:
      #   - 80-Ideas-Intro.qmd
  page-footer: 
    center: "<a href='https://linktr.ee/rafaeldcsantos'>Rafael Santos</a>" 


format:
  html:
    theme:
      - spacelab
    toc: true
    css: Resources/CSS/custom.css
    bibliography: CAP394.bib
    date: last-modified
    date-format: long



