---
title: "About this Course"
format: 
  html: 
    css: Resources/CSS/custom.scss
bibliography: CAP394.bib      
---

These pages contains the material used for the course *Introduction to Data Science*, part of the [curriculum](https://www.gov.br/inpe/pt-br/area-conhecimento/posgraduacao/cap/catalogo-de-disciplinas) of the [Graduate Program in Applied Computing](https://www.gov.br/inpe/pt-br/area-conhecimento/posgraduacao/cap), offeredy by the [Brazilian National Institute for Space Research](https://www.gov.br/inpe/pt-br). 

The course is usually offered in the [second term](https://www.gov.br/inpe/pt-br/area-conhecimento/posgraduacao/calendario-academico) of each year, **exclusively asynchronously**. Although the material is in English, classes are usually taught in Portuguese.

## Syllabus

&ensp; &ensp; _What is Data Science? Why Data Science exists as a discipline?_<br>
&ensp; &ensp; _The role of a Data Scientist. Other roles and tasks in Data Science._<br>
&ensp; &ensp; _Data Collection and Discovery. Data Provenance and Annotation._ <br>
&ensp; &ensp; _Data Representation: Flat Files, Databases, Tidy Data._<br>
&ensp; &ensp; _Introduction to Analytics, Exploratory Data Analysis and Machine Learning._<br>
&ensp; &ensp; _Reproducible Research. Data-based products._ <br>
&ensp; &ensp; _Examples of applications, case studies and project development._<br>

### Bibliography

For a good all-around reference in Data Science see _The Art of Data Science: A Guide for Anyone who works with Data_ [@peng2015art] or _Doing Data Science: Straight Talk from the Frontline_ [@doingdatascience2013].

For information on data scientists profiles see _Analyzing the Analyzers: An Introspective Survey of Data Scientists and Their Work_ [@analyzingtheanalyzers] or _Data scientists at work_ [@gutierrez2014data]. 


::: underconstruction-block 
<div class="title">Under Construction</div>
This material is continually being revised and improved. 
:::

## Schedule for 2025 {#Schedule}

For the second term of 2025 our schedule is **Fridays, from 1:30PM to 5:30PM.**

| Day        | Topics                                                                             |
|------------|----------------------------------------------------------------------------------|
| June 20    | <span style="color:red;">Lectures suspended today</span>  |
| June 27    | Introduction to the course. Reading of [About the Course](00-Lectures-Intro.qmd) and [What is Data Science?](01-Lectures-WhatIs.qmd) lectures, rules for [evaluation](index.qmd#homework).|
| July  4    | Reading of [Skills for Data Science](02-Lectures-Skills.qmd) lecture. Q&A about the  [first homework](index.qmd#homework) (if needed).     |
| July 11    | |
| July 18    | |
| July 25    | |
| August 1   | |
| August 8   | |
| August 15  | |
| August 22  | |
| August 27  | |
| September 5| Presentation and comments on the [Capstone Project](index.qmd#homework).|
: {tbl-colwidths="\[20,80\]" .striped .hover}





<!-- | Day      | Topics                                                                             |
|----------|----------------------------------------------------------------------------------|

|July 5    | Reading of [Data](03-Lectures-Data.qmd).   Presentation and comments on the [first homework](index.qmd#homework).   |
|July 12   |  Reading of the [Supermarket Basket Analysis](53-Projects-Supermarket.qmd) case.<br>Presentation and comments on the [second homework](index.qmd#homework).       |
|July 19   |      |
|July 26   | <span style="color:red;">Lectures suspended today</span>   |
|August 2  |  Short introduction to models and classification (lecture notes still under construction)                                                                                |
|August 9  | Let's talk about the capstone project?    |
|August 16 |         Presentation and comments on the [third homework](index.qmd#homework).                                                                           |
|August 23 |  Models, classification and clustering (probably)                                                                           |
|August 30 |      |

: {tbl-colwidths="\[20,80\]" .striped .hover} -->

## Homework

| Assignment                                                                       | Due date (*before that day's lecture!*) |
|----------------------------------------------------------------------------------|----------|
| [Homework #1 ](00-Homework-01.qmd)                    | July 4   |
| TBD                          | August  9 |
| Capstone Project            | September 5 |

: {tbl-colwidths="\[40,60\]" .striped .hover}
